name: job
on: workflow_dispatch
env:
  App_ENV: "dev"

jobs:
  envjob:
    env:
      APP_ENV: "UAT"
    runs-on: ubuntu-latest
    steps:
      - name: printenv
        run: echo "welcome to $APP_ENV"
